### ISSUE TITLE
Prepare a build script for DAG-MCNP5 for use by a generic user on a linux machine

### ISSUE THREAD

**Issue by gonuke** [svalinn/DAGMC#12]
Prepare a build script that allows an external user on a "typical" linux distribution to build DAG-MCNP5.  They'll have to indicate the path to certain libraries or source code (e.g. MCNP5) on the command line.

**Comment by ljacobson64** [comment]
These exist now (https://github.com/ljacobson64/DAGMC/tree/develop/tools/build) but they're out of date. However, we encourage people to read the documentation and build things themselves now so I'm closing this.
