### ISSUE TITLE
Study impact of small features on DAG-MCNP performance

### ISSUE THREAD

**Issue by gonuke** [svalinn/DAGMC#18]
The hypothesis is that small features in a model have a small impact on ray tracing performance thanks to the OBB Tree.

This stand along project includes a number of numerical experiments to test/validate/disprove this hypothesis.

Experiment 1-A: Start with a cube, modeled in both native MCNP and DAG-MCNP.  Add a "notch" to that cube at the corner, such as removing a rectangular prism from an edge.  The edge length of the notch is  d.  Repeat this with more notches of the same edge length.

Experiment 1-B: Similar to (1-A) but keep the total size of the detail fixed and the edge length shrinks as more notches are added.

Experiment 2-A,2-B: Repeat the above starting with a sphere and rectangular notches.

Experiment 3-A,3-B: Repeat experiment 2-(A,B) with other shaped details.

Determine which metrics will be compared, including at least the ray-firing time per ray.  Some experiment design will be necessary to determine fair measures of these quantities.

**Comment by makeclean** [comment]
This has been done.
