### ISSUE TITLE
Additional tests are required for the dagmc_tag_material script

### ISSUE THREAD

**Issue by makeclean** [svalinn/DAGMC#257]
Additional unit tests are required, specifically a test on the function tag_to_script, to ensure all groups are found. I suggest we make a system call on this test, for example

```
  mbsize -ll test.h5m  | grep 'mat:'
```

Will give all group names of the form "mat:*", I suggest we read the standard out of this result and compare against the vector of tags as a result of running the tag_to_script function.

**Comment by ljacobson64** [comment]
Don't think we use this script anymore
