### ISSUE TITLE
Negative track length error in DAGMC tet mesh tallies

### ISSUE THREAD

**Issue by gonuke** [svalinn/DAGMC#26]
One of the warnings that can arise from the tetrahedral mesh tallies is the "Negative Track Length" warning.  This appears to happen when a ray passes through triangular faces of a tetrahedron in the "wrong order".  That is, a ray identifies an exit point from a tetrahedron that is behind the entry point.

We need to better understand when this happens, and what we can do to prevent it.

**Comment by makeclean** [comment]
Fixed as of commit ed40aec698e9a7ec58933679ea6e0d2eedd0164a
