### ISSUE TITLE
Get nuc_data_path programmatically

### ISSUE THREAD

**Issue by julamot** [svalinn/DAGMC#351]
PyNE 0.5.0 moves the location of the pyne install:

old:
.local/lib/python2.7/site-packages/pyne
new:
.local/lib/python2.7/site-packages/pyne-0.5.0_rc1-py2.7.egg/pyne

This is where nuc_data.h5 is located, and uwuw_preproc currently gets this location from a command line switch.

I would suggest giving a default location:
import pyne
filename = pyne.nuc_data

This produces 
/userspace/z/zachman/.local/lib/python2.7/site-packages/pyne-0.5.0_rc1-py2.7.egg/pyne/nuc_data.h5 
on my system.  Since the location of nuc_data.h5 will now change with package updates, getting it dynamically will be more robust.

**Comment by makeclean** [comment]
The material library will often be problem specific, for example the Pyne library is an incomplete collection, I expect most users to have their own which will be in a custom location.

**Comment by makeclean** [comment]
Redundant.
