### ISSUE TITLE
gcad path handled incorrectly

### ISSUE THREAD

**Issue by elliottbiondo** [svalinn/DAGMC#368]
When running DAG-MCNP, the `gcad` argument should specify the path to the CAD geometry file. It looks like this path is being appended to `pwd`, hence the output below. Notice that two paths beginning with `/home/` are appended:

```
The file /home/biondo/FNG_ITER/p_trans_analog/t17_test//home/biondo/benchmarks/fng_iter/adapted_from_sinbad/photon/mcnp_g_adapted_with_detectors_zip.h5m does not exist or is read protected```

**Comment by gonuke** [comment]
Can you include the actual value of `pwd` and the command-line that you entered?

**Comment by elliottbiondo** [comment]
`pwd` was:
`/home/biondo/FNG_ITER/p_trans_analog/t17_test/`

the command was something like:
```
mpirun -np 256 mcnp5.mpi i=<input_file> gcad=/home/biondo/benchmarks/fng_iter/adapted_from_sinbad/photon/mcnp_g_adapted_with_detectors_zip.h5m
```

**Comment by makeclean** [comment]
This is from the uwuw class, I can take a look later
