### ISSUE TITLE
DATAPATH and xsdir command line argument not working as intended

### ISSUE THREAD

**Issue by ljacobson64** [svalinn/DAGMC#380]
My understanding is that there are two ways to specify where your data is for a run:

* 1. Set the $DATAPATH environment variable, and MCNP will search for a file called "xsdir" in that path.

When doing this, MCNP always finds xsdir, but it doesn't always find the cross section library specified in xsdir. Specifically, if $DATAPATH is the same as it was during compilation, it will find the cross sections, but if it is different, then it will not.

* 2. Specify "xsdir=" on the command line, and MCNP will use the specified file.

This appears to work only if the file specified is in the same directory as the one where MCNP is run. So if the files "testdir1" and "testlib1" are in the current directory, then using "xsdir=testdir1" will work. But if testdir1 and testlib1 are 2 levels down, using "xsdir=../../testdir1" will not work.

The reason any of this matters is that some of the tests in DAG-MCNP-TESTING have command line arguments like "xsdir=../../testdir1", and MCNP isn't finding the cross sections.

**Comment by Baaaaam** [comment]
there is actually more way to define the xsdir, or to use some....

>The directory where the data libraries are stored is named datapath. The XSDIR directory file can be renamed by item 1. The search hierarchy to find XSDIR and/or the data libraries is:
>1. XSDIR=cross-sectiondirectoryfilenameontheMCNP6executionline,
>2. DATAPATH=datapathintheINPfilemessageblock,
>3. the current working directory,
>4. the DATAPATH entry on the first line of the XSDIR file,
>5. the UNIX environmental variable setenv DATAPATH datapath,
>6. the individual data table line in the XSDIR file (see below under Access Route), or
>7. the directory specified at MCNP6 compile time in the BLOCK DATA subroutine. 

*from the MCNP6 manual*

if the XSDIR is not given in the MCNP command line and the DATAPATH is not defined, MCNP6 will try to find an xsdir file in the current working directory.

Note that, the order of preferences between the different possibilities could depend on the MCNP version... 


I hope those information could help...

BaM

**Comment by makeclean** [comment]
@ljacobson64 you may also want to try defining the path expliclty rathe than ../../ try the full path

**Comment by makeclean** [comment]
I also don't think this is a DAGMC issue, I think this is a generic MCNP feature

**Comment by ljacobson64** [comment]
My mistake, I was using my own fork which didn't have Andy's fix which is why it wasn't working...
