### ISSUE TITLE
Consistent CMake variable names

### ISSUE THREAD

**Issue by Pshriwise** [svalinn/DAGMC#391]
This is a small issue, but I wanted to bring it up before I forget about it

When building, it would be nice if the variables always read as -D__BUILD or -DBUILD__ this way people won't have to check variable each time they want to configure for a known component of dagmc. For examply: If they want to build FLUKA, its always FLUKA_BUILD. If they want MPI, its always MPI_BUILD. 

This is mostly to reduce confusion, but there may be a very good reason I don't know about for why they are named this way.

**Comment by ljacobson64** [comment]
We have this now
