### ISSUE TITLE
cgm install tag

### ISSUE THREAD

**Issue by Pshriwise** [svalinn/DAGMC#396]
Currently we're directing users to checkout a tag 12.2.2 if they're building CGM with Cubit 12.2 but there is no such tag in the CGM repo. Should we redirect them to either the 12.2.0 or 12.2.1 tag instead?

**Comment by Pshriwise** [comment]
@makeclean @gonuke Thoughts on this?

**Comment by makeclean** [comment]
Personally I doubt its a problem given the we will be refactoring our workflow with Trelis and its internal version of CGM.

**Comment by Pshriwise** [comment]
I'm wondering what our test builds are currently using for Cubit 12.2 or do we not test that at this point?

**Comment by gonuke** [comment]
Clsoing because we no longer want to refer people to CGM/Cubit
