### ISSUE TITLE
MOAB Team have moved CMake file

### ISSUE THREAD

**Issue by makeclean** [svalinn/DAGMC#409]
When MOAB is built it produces a MOABConfig.cmake file which we rely on to find all the correct settings for MOAB. It was previously in the lib folder of an install, it has now been moved to lib/cmake/MOAB. Our method for finding MOAB needs updating.

**Comment by makeclean** [comment]
Actually, its only when you build with CMake that the config file is in this new place, either way our FindMOAB.cmake should be able to handle it.

**Comment by ljacobson64** [comment]
Addressed by #507. I think?
