### ISSUE TITLE
Reintroduce simple workflow

### ISSUE THREAD

**Issue by makeclean** [svalinn/DAGMC#415]
It is convenient for those users that do not want to use UWUW to be able to interact with FluDAG in a more simplistic way. Therefore we should reintroduce the first method we used to define materials tags for FluDAG. Namely by adding volumes to groups of the form mat:NAME where NAME is an 8 character long string, which immediately produces the appropriate ASSIGNMAt card. This can be done in a similar way to how we interact with the legacy MCNP workflow, something like

```
UWUWU *uwuw = new UWUW("filenaname");
if ( uwuw->material_library().length() == 0 ) { 
   simple_workflow();
else
  uwuw_workflow();
```

Such that if UWUW materials are found, then we use the UWUW workflow, otherwise assume its the simple one.

**Comment by ljacobson64** [comment]
I think this was implemented in #465
