### ISSUE TITLE
Legacy MCNP ACIS importance tagging doesn't work for certain MCNP6 particles

### ISSUE THREAD

**Issue by ljacobson64** [svalinn/DAGMC#422]
ACIS volumes are added to groups like `imp.n_1` to specify that the neutron importance for that volume is 1. MCNP5 only `n`, `p`, and `e` particle types, so this works fine. MCNP6, however, has quite a few more particle types, some of which are symbols. Two of these symbols, `|` and `~`, cause problems. This is what happens when you try to assign a group with the name of `imp.|_1` to a volume:

```
CUBIT> group "imp.|_1" add volume 1
WARNING: Entity name 'imp.|_1' can't be used in commands.
         Additional name 'imp.__1' assigned.
Creating imp.__1 (Group 2)
Group Entity 'imp.__1', 'imp.|_1' (Id = 2)
It owns/encloses 1 entity: 1 volume.
Journaled Command: group "imp.|_1" add volume 1
```

The group actually assigned ends up being `imp.__1` instead.

However, it turns out that if we switched the naming scheme to replace the `.` with a `:` and the `_` with a `=`, all of the MCNP6 particle types will work:

```
CUBIT> group "imp:|=1" add volume 1
WARNING: Entity name 'imp:|=1' can't be used in commands.
         Additional name 'imp___1' assigned.
Creating imp:|=1 (Group 2)
Group Entity 'imp:|=1', 'imp___1' (Id = 2)
It owns/encloses 1 entity: 1 volume.
Journaled Command: group "imp:|=1" add volume 1
```

The warning message still shows up, but the correct group name is assigned.

Thus I propose to change the naming scheme from `imp.n_1` to `imp:n=1`. This also has the advantage of being the exact same way you would specify importances on an MCNP cell card.

**Comment by ljacobson64** [comment]
Follow up: apparently `=`, `|`, and `~` don't get transferred to the faceted file when running dagmc_preproc. So now I propose to keep the original naming scheme for all particles other than `|` and `~`, and use the ASCII code for those two. For example, instead of `imp.|_1`, we'd use `imp.124_1` because 124 is the code for `|`.

**Comment by ljacobson64** [comment]
Or perhaps we could use `1` and `2` so they can remain one character and avoid a lot of unnecessary code

**Comment by makeclean** [comment]
Solved with the new naming scheme & deprecation of legacy workflow
