### ISSUE TITLE
Add CLANG to Docker CI Image 

### ISSUE THREAD

**Issue by makeclean** [svalinn/DAGMC#430]
Given @kkiesling's recent summer of fun with OS/X we should probably at the very least add Clang to the CI Docker Image and modify the test matrix so we get versions two test streams (Clang and GCC)

**Comment by kkiesling** [comment]
I think that would be a good idea, especially because developers at national labs tend to use OS/X. I agree that GCC and Clang are both necessary.

**Comment by ljacobson64** [comment]
Addressed by #511
