### ISSUE TITLE
Add capability for programs built on top of make_watertight

### ISSUE THREAD

**Issue by pshriwise** [svalinn/DAGMC#431]
Some background: Regression tests for `make_watertight` are in a separate [repository](https://github.com/pshriwise/mw_reg) because they rely on models which we can't make publicly accessible. Currently, the models are kept in CAE space and are required to be gathered by the user if they want to run the regression tests. These tests are run weekly on my work machine with an indicator to me if they fail. (This is a separate problem to be faced later.)

Problem at hand: The regression test repository builds a test program for the models based on a lot of the `make_watertight` code. As such, it would be nice to have the same capability with the version of `make_watertight` here in DAGMC. There are multiple ways to do this, but before I embark on any of them I'd like to figure out which is best:

1) In make_watertight's previous home, [moab_tools](https://github.com/svalinn/moab_tools) I wrote a branch which created a library of the critical functions for `make_watertight` and built my test program using that. I could repeat this in DAGMC. This might require the installation of some make_watertight headers which could be done under their own `make_watertight` directory.

2) I could bring the test program into DAGMC and build it here to run my test scripts for the regression test models using that program instead. 

If there are other suggestions for better methods of going about this please feel free to suggest them here!

**Comment by makeclean** [comment]
You can also add encrypted environment variables, these are only available
for in repo builds, i.e. not PR's. If you're happy with the tests being run
nightly, then as long as you can serve them to travis you will be ok. You
can add a line to the travis.yml file the does a wget or rsync.

The key part is serving those files to travis.

**Comment by Pshriwise** [comment]
I'd be more than fine with running the tests nightly (much better than their frequency now). 

With my understanding that this aligns with option 2) above, I would bring the test programs into DAGMC. These programs *wouldn't* be part of a standard DAGMC build/install, but travis *would* build and run them nightly after getting the test models from CAE?

**Comment by makeclean** [comment]
That's right. How long are the tests? Travis has a time limit of 30 mins
for the free builds.

**Comment by Pshriwise** [comment]
They take 6m20s real time on my machine.

**Comment by makeclean** [comment]
Should be no issue then. I would say as long as you can find a secure way
to serve the files, then there should be no barriers

**Comment by Pshriwise** [comment]
Maybe I'll try shooting CAE an email and see what they suggest on that topic.

**Comment by gonuke** [comment]
ping @pshriwise

**Comment by pshriwise** [comment]
This is sorted.

The regression test files are pulled from a secure location using a Travis environment variable for authorization. These tests are run only if not a PR.

I'll try to track down the PR I made for these tests...

**Comment by pshriwise** [comment]
Found it. #441

**Comment by gonuke** [comment]
Resolved by #441
