### ISSUE TITLE
[make_watertight] Trelis handling of Spheres

### ISSUE THREAD

**Issue by makeclean** [svalinn/DAGMC#436]
Trelis handles spheres differently to older version of cubit, where it would contain a point curve (zero length curve). This in itself isn't a massive problem, but the logic of make_watertight is such that if there are no curves to a surface, the surface is deleted. make_watertight needs to do additional checks when a surface has no curves, for example it could check to see if the surface is closed, maybe by skinning.

**Comment by Pshriwise** [comment]
@makeclean I think I have this issue resolved as well now. Please try [this branch](https://github.com/pshriwise/DAGMC/fix_trelis_sphere)

**Comment by makeclean** [comment]
Yeah, that's perfect :)

**Comment by makeclean** [comment]
PR away!

**Comment by Pshriwise** [comment]
Taken care of in #438
