### ISSUE TITLE
[make_watertight] When a volume has no surfaces, we should delete the volume

### ISSUE THREAD

**Issue by makeclean** [svalinn/DAGMC#437]
When make_watertight encounters a surface with no curves, it deletes the surface, but when a volume has no surfaces it does not always delete the volume.

**Comment by Pshriwise** [comment]
@makeclean can you try out [this branch](https://www.github.com/pshriwise/DAGMC/tree/fix_mw_empty_voll) and see if it fixes that problem with the model we were working with yesterday?

**Comment by makeclean** [comment]
Also your current head is good for this too:)

**Comment by Pshriwise** [comment]
Yeah I think I'll rename my latest and PR.

**Comment by Pshriwise** [comment]
...as soon as I add that sample problem you provided as a test, @makeclean

**Comment by Pshriwise** [comment]
Addressed in #438
