### ISSUE TITLE
Uninitialized object in `dagmcwritefacets`

### ISSUE THREAD

**Issue by pshriwise** [svalinn/DAGMC#518]
Thought we'd fixed this already...

[This line](https://github.com/svalinn/DAGMC/blob/develop/mcnp/mcnp_funcs.cpp#L142) is sometimes called before, sometimes after other methods in `mcnp_funcs.cpp`. When the object `workflow_data` isn't initialized, the result is a seg fault when writing facets to file.

**Comment by pshriwise** [comment]
@makeclean informed me that this is no longer the case with the most recent patches to MCNP5/6, but we concluded that moving the initialization of `workflow_data` into  the `dagmcinit` method is more logical. 

I will submit a PR shortly with this change.

**Comment by gonuke** [comment]
resolved in #530
