### ISSUE TITLE
GCC Version on CI

### ISSUE THREAD

**Issue by makeclean** [svalinn/DAGMC#522]
TAE use GCC 4.8.1 on their cluster  we should ensure we works with this version for future changes.

**Comment by ljacobson64** [comment]
I don't think there are any good ways of getting GCC 4.8.1 on the CI other than building it from source. The compilers you get from the package managers are always the latest patch version, which for version 4.8 is 4.8.5.

**Comment by gonuke** [comment]
We've updated this many times - closing until it arises again
