### ISSUE TITLE
[Style Guide] Create separate build for testing style

### ISSUE THREAD

**Issue by pshriwise** [svalinn/DAGMC#539]
Stemming from discussions in #537, it would be beneficial to create a separate build in Travis for checking the code formatting and style in a pull request. This will make it easier to identify when CI has failed due to style guide issues.

**Comment by pshriwise** [comment]
One specific improvement:

  - Error in the Travis output should be clear about why the test has failed using some standard message rather than displaying the diff

**Comment by ljacobson64** [comment]
Addressed by #541
