### ISSUE TITLE
Pyne mesh source sampling does not work with MCNP6

### ISSUE THREAD

**Issue by ljacobson64** [svalinn/DAGMC#551]
MCNP6 gives build errors due to undefined variables if you try to build it with pyne mesh source sampling capability.

**Comment by shimwell** [comment]
Does this mcnp6 source.F90 help?
https://github.com/Shimwell/DAGMC/blob/pyne-source/mcnp/mcnp6/Source/src/source.F90

**Comment by shimwell** [comment]
The fork has been tidied up and now either the mcnp6 or the mcnp5 source.F90 are included in the DAGMC/src/mcnp/CMakeLists.txt with help from @makeclean 

I shall make a PR with your pyne-source branch

**Comment by ljacobson64** [comment]
Addressed by #604
