### ISSUE TITLE
DAGMCConfig.cmake file error

### ISSUE THREAD

**Issue by makeclean** [svalinn/DAGMC#557]
Even when building without dagtally, the .cmake file includes a -ldagtally link flag.

**Comment by pshriwise** [comment]
Yeah that should be fixed. 

I'm thinking that building a list of created libraries in DAGMC is the way to go, adding to it each time `add_library` is called. 

I'm not sure how to handle static/shared versions though @makeclean. Do you think we should populate two lists, `DAGMC_SHARED_LIBS` and `DAGMC_STATIC_LIBS`?

**Comment by ljacobson64** [comment]
I think this was fixed by #555.
