### ISSUE TITLE
DAGMCNP6 compiler bug

### ISSUE THREAD

**Issue by shimwell** [svalinn/DAGMC#562]
Hi all

I am trying to compile DAGMCNP with mcnp version 6.1.1 beta and came across a few errors

```
[ 97%] Building Fortran object src/mcnp/mcnp6/CMakeFiles/mcnp6.dir/Source/src/partisn/partisn_read_xslibb.F90.o
[ 97%] Building C object src/mcnp/mcnp6/CMakeFiles/mcnp6.dir/Source/src/utils/c_ioroutines.c.o
[ 97%] Linking Fortran executable mcnp6
/usr/bin/x86_64-linux-gnu-ld: cannot find -lieee
collect2: error: ld returned 1 exit status
src/mcnp/mcnp6/CMakeFiles/mcnp6.dir/build.make:25110: recipe for target 'src/mcnp/mcnp6/mcnp6' failed
make[2]: *** [src/mcnp/mcnp6/mcnp6] Error 1
CMakeFiles/Makefile2:1506: recipe for target 'src/mcnp/mcnp6/CMakeFiles/mcnp6.dir/all' failed
make[1]: *** [src/mcnp/mcnp6/CMakeFiles/mcnp6.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
jshim@jshim-B250M-D3H:~/dagmc_bld/DAGMC/DAGMC/bld$ 
```
It appears that gfortran-7 / gcc-7 no longer accepts the -mieee-fp flag

I have commented out the following line in the mcnp/mcnp6/CMakeLists.txt file and this works for my particular system
```
set(CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS} -mieee-fp")  
```

However others have had the same issue and solved it like this [https://sourceforge.net/p/plplot/mailman/message/36155710/](https://sourceforge.net/p/plplot/mailman/message/36155710/) - it appears that glibc has dropped that particular part of addressing IEEE rounding and is now native to the glibc library. Since this is sensitive to the glibc version, this implies a linux distro/version issue. However the fix in the above link should fix that problem, I think?

I have discussed this with @makeclean

**Comment by ljacobson64** [comment]
This is my personal workaround:

```
sudo apt install libieee1284-3-dev
sudo ln -s /usr/lib/x86_64-linux-gnu/libieee1284.so.3 /usr/lib/libieee.so
sudo ln -s /usr/lib/x86_64-linux-gnu/libieee1284.a /usr/lib/libieee.a
```

**Comment by pshriwise** [comment]
I don't think we should ask users to modify their system libraries... this does provide a little more insight into the issue though!

**Comment by gonuke** [comment]
I assume this error is not still an issue - can anyone confirm (and close the issue)?

**Comment by shimwell** [comment]
Ah sorry I don't have access to MCNP to check, but happy to close it as there are two work arounds in the text above. Feel free to reopen if anyone comes along this issue in the future
