### ISSUE TITLE
News policy

### ISSUE THREAD

**Issue by ljacobson64** [svalinn/DAGMC#567]
There have been a few PRs approved recently (some by me) which didn't include a news file. We should do one of these things:

* Come up with rules for which PRs need to contain a news file
* Require every PR to contain a news file and have the reviewers do a better job of making sure it exists
* Require every PR to contain a news file and somehow get the CI to notice whether a new news file has appeared and have it fail the tests if it doesn't find one

**Comment by pshriwise** [comment]
Good call. I think the first and third are great solutions. We should be able to have travis do a check for diff (an addition, more specifically) to the news file via comparison to develop. We do this for one of the runs in the matrix and only if a `TRAVIS_PULL_REQUEST` check is positive.

**Comment by pshriwise** [comment]
If we wanted to require it for **every** PR that is...

**Comment by gonuke** [comment]
This was resolved by #610 (or about then)
