### ISSUE TITLE
Include an astyle binary with DAGMC

### ISSUE THREAD

**Issue by ljacobson64** [svalinn/DAGMC#568]
Pros/cons of including an astyle binary with DAGMC? We could include a very short script which runs astyle on the repo exactly as will occur on the CI. This should reduce the barrier to entry for submitting PRs. It would also get rid of the current astyle version problem where the only version that works is 3.0.1. (3.1 produces slightly different output in a single file, and 2.x.x segfaults.)

A quick glance at the License section on the [astyle website](http://astyle.sourceforge.net) leads me to believe that we can probably do this.

**Comment by makeclean** [comment]
Like we used to?

**Comment by ljacobson64** [comment]
I'm not aware of us ever having supplied a binary

**Comment by pshriwise** [comment]
True but we supplied a static source and built it with CI. Pretty similar.

**Comment by makeclean** [comment]
Yeah we used to supply source for a fixed version rather than a binary. For the exact same reason you state in fact. No binary due to all the different systems, osx, windows, different Linux distro, IBM power 8 etc

**Comment by gonuke** [comment]
deprecated by move to `clang-format`
