### ISSUE TITLE
Required MOAB shared/static build.

### ISSUE THREAD

**Issue by pshriwise** [svalinn/DAGMC#571]
[This line](https://github.com/svalinn/DAGMC/blob/develop/cmake/FindMOAB.cmake#L84) in FindMOAB.cmake causes us to require that MOAB was built with shared libraries... do we want to always require this. Can we require it only if DAGMC is being built with static libs? 

I know a shared static and shared build is now the default for DAGMC, but as it stands we don't present a pathway to building with shared libraries at all. Same is true for a static lib only pathway...

**Comment by ljacobson64** [comment]
I can try to come up with a way to fix this. I imagine it'll look something like adding the cmake variables `CMAKE_BUILD_STATIC_LIBS` and `CMAKE_BUILD_SHARED_LIBS` that default to `ON` but are allowed to be turned off. Then, we'll only search for static/shared external libraries (e.g. MOAB) as needed.

**Comment by pshriwise** [comment]
Sounds good. The current state breaks some downstream work so the sooner the better. :)

**Comment by ljacobson64** [comment]
@pshriwise same question here... did #572 solve this?

**Comment by pshriwise** [comment]
I think so.... let me double check and then I'll close it.

**Comment by pshriwise** [comment]
It seems to me we're good, yup. For anyone who might find this issue in the future, the default is to build both static and shared libraries as #572. To build DAGMC with only static or shared libraries the `BUILD_STATIC_LIBS` and `BUILD_SHARED_LIBS` options will need to be turned off in the cmake command. (e.g. `-DBUILD_STATIC_LIBS=OFF`)
