### ISSUE TITLE
Add Community Best Practices

### ISSUE THREAD

**Issue by kkiesling** [svalinn/DAGMC#587]
Add community best practices [here](https://github.com/svalinn/DAGMC/community). The [DAGMC-viz repo](https://github.com/svalinn/DAGMC-viz/community) has most of these already and can be used as a guide.

**Comment by kkiesling** [comment]
Note: a News file should be required for every PR (add to PR guidelines) as discussed in #567.

**Comment by ljacobson64** [comment]
Solved by #589
