### ISSUE TITLE
Build with MacOS Mojave (gfortran linking) 

### ISSUE THREAD

**Issue by bam241** [svalinn/DAGMC#627]
I just experienced some issue to build `DAGMC` on MAC.
Configuration: 
- MacOS mojave, 
- `gfortran` installed from https://gcc.gnu.org/wiki/GFortran
- `hdf5`: from macport
- compiler: native macOS `clang`.

Issue:
------
```
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/dagmc/libdagmc.dylib] Error 1
make[1]: *** [src/dagmc/CMakeFiles/dagmc-shared.dir/all] Error 2
make: *** [all] Error 2
```

**?temporary? solution:**
----------------------
add `-DCMAKE_CXX_FLAGS="-L/usr/local/gfortran/lib"` to the `cmake` configuration line

I did not find a better flag to set (I guess it is only required during the linking....
I got a lot of warning"
`clang: warning: argument unused during compilation: '-L/usr/local/gfortran/lib' [-Wunused-command-line-argument]`

I have tried several LINKER_FLAGS without success (`CMAKE_MODULE_LINKER_FLAGS_INIT`, `CMAKE_EXE_LINKER_FLAGS_INIT`, `CMAKE_SHARED_LINKER_FLAGS_INIT`,`CMAKE_MODULE_LINKER_FLAGS`, `CMAKE_EXE_LINKER_FLAGS`, `CMAKE_SHARED_LINKER_FLAGS`  )

**Comment by makeclean** [comment]
This is due to an oversight in the FindMOAB.cmake file

```# Find MOAB library (shared)
if (BUILD_SHARED_LIBS)
  set(CMAKE_FIND_LIBRARY_SUFFIXES ${CMAKE_SHARED_LIBRARY_SUFFIX})
  find_library(MOAB_LIBRARIES_SHARED
    NAMES MOAB
    HINTS ${MOAB_LIBRARY_DIRS}
    NO_DEFAULT_PATH
  )
  list(APPEND MOAB_LIBRARIES_SHARED lapack blas gfortran quadmath)
endif ()
```
Even when not needed by MOAB, we still ask for gfortran etc to be added. I think those lines shouldnt be there.

**Comment by ljacobson64** [comment]
If I comment that line and then try to build DAGMC, I get this error:
```
../libdagtally.so: undefined reference to `dspsv_'
collect2: error: ld returned 1 exit status
src/tally/tests/CMakeFiles/test_CellTally.dir/build.make:111: recipe for target 'src/tally/tests/test_CellTally' failed
make[2]: *** [src/tally/tests/test_CellTally] Error 1
CMakeFiles/Makefile2:911: recipe for target 'src/tally/tests/CMakeFiles/test_CellTally.dir/all' failed
make[1]: *** [src/tally/tests/CMakeFiles/test_CellTally.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by makeclean** [comment]
That's a lapack routine, called directly from dagtally. This is an interesting one, so when Moab is built with fortran and blas/lapack you can obviously do what is there right now. But since we can't when Moab hasn't got it, there is an explicit dagmc dependency on lapack/blas and therefore the lines target_link_libs should probably be done in the dagtally cmake file

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ljacobson64** [comment]
I submitted #634 to fix this, although I'm not sure how much help this will be to @bam241 since he still won't be able to build `libdagtally` since it still requires `libgfortran`

**Comment by ljacobson64** [comment]
@bam241 It seems like you built gfortran from source. Is this true? Can you not use a package manager?

**Comment by bam241** [comment]
I could, but it is a nice click and install think:
https://github.com/fxcoudert/gfortran-for-macOS/releases

I used version 4.9 (I don't remember exactly why, I think it newer version where not working...)

I could have use the MacPorts version, but it come with a lot of other deps....

in MacPorts you have to install `gcc48` to get GFortran... the installer was simpler...

**Comment by ljacobson64** [comment]
In your current installation, what is the location of `libgfortran.so`?

**Comment by gonuke** [comment]
I suppose that `libgfortran` is not in the `LD_LIBRARY_PATH` so no wonder it doesn't get found?

**Comment by ljacobson64** [comment]
I don't think `LD_LIBRARY_PATH` would do anything here. Perhaps another environment variable.

**Comment by ljacobson64** [comment]
I just had an idea. @bam241 can you try this again but add this cmake option:
```
-DCMAKE_Fortran_COMPILER=/path/to/gfortran
```

And if that doesn't work, can you try it again (leaving that cmake option the same) with this environment variable set:
```
export LIBRARY_PATH=/path/to/libgfortran.so
```

[Discussion of the difference between `LIBRARY_PATH` and `LD_LIBRARY_PATH` here](https://stackoverflow.com/questions/4250624/ld-library-path-vs-library-path/4250666#4250666)

**Comment by bam241** [comment]
`ls /usr/local/gfortran`
returns:
`bin     include lib     libexec share`
`ls /usr/local/gfortran/lib/libgfortran.*` returns:
`lib/libgfortran.3.dylib lib/libgfortran.a       lib/libgfortran.dylib   lib/libgfortran.la      lib/libgfortran.spec`
and hobviously there is more lib in that folders... (no more named libgfortran tho)

sorry for the delay

**Comment by bam241** [comment]
it seems that: 
`export LIBRARY_PATH=/usr/local/gfortran/lib`
does the trick

As expected adding it to the LD_LIBRARY_PATH do not work...

**Comment by bam241** [comment]
I think the problem is either:
- bad `LIBRARY_PATH`
- `cmake` only search for the executable (and find them...) but not for the path for the library

**Comment by Jinwu-CAI** [comment]
I also suffered this problem and now it is solved.

My system is macOS Catalina 10.15.4.

gfortran is contained in gcc, and I can not find gfortran/lib. Finally I found that all are in lib of gcc. After 

> export LIBRARY_PATH=/usr/local/Cellar/gcc/9.3.0/lib/gcc/9  

'make' was well done.

**Comment by ahnaf-tahmid-chowdhury** [comment]
I think the issue is solved and we are ready to close.
