### ISSUE TITLE
Assignment of material's temperature by python code should be remained when using DAGMC-OpenMC

### ISSUE THREAD

**Issue by D-Benjamin** [svalinn/DAGMC#631]
Hi All,
    New feature of using CAD-Based Geometries have been released in latest version. However, the way of assigning temperature have changed. We can not assign material's temperature by:

```
u235 = openmc.Material(name="fuel")
u235.add_nuclide('U235', 1.0, 'ao')
u235.set_density('g/cc', 11)
u235.temperature = 900         #This line will be no use even if you add it
```

   Materials' temperature can not be assigned, the only way to assign temperature is by using "Cubit/Trelis" when we creating geometry model:

`CUBIT> group "temp:900" add vol x` ([here is the link](https://svalinn.github.io/DAGMC/usersguide/codes/openmc.html#temperatures))

Thus, it will be very inconvenient when we want to change the materials' temperature, we have to launch "Cubit/Trelis" to modify it. In particular, if we want to achieve a coupling between the neutronics and thermal-hydraulics(such as between OpenMC and a thermal-hydraulics code), we need exchange the power distribution, materials' temperature and density distribution by editing script. It is impossible to exchange large amounts of data manually by launching "Cubit/Trelis" and enter "`CUBIT> group "temp:900" add vol x`" every time. So I highly recommend that assignment of material's temperature by python code should be remained when using DAGMC-OpenMC.

Best Regards,
Benjamin

**Comment by pshriwise** [comment]
Thank you for reporting this @D-Benjamin! I agree that these operations should work for CAD geometries as well. I'll look into it shortly.

**Comment by D-Benjamin** [comment]
@pshriwise Thanks for your reply! By the way, if we don't assign temperature by "`CUBIT> group "temp:900" add vol x`", the temperature will be defaulted to 293.6K rather than 900K which assigned by python code: "`u235.temperature = 900`"

**Comment by pshriwise** [comment]
I'm going to close this issue in favor of the [issue related to this](https://github.com/openmc-dev/openmc/issues/1293) in the OpenMC repo, where the logic related to this temperature assignment resides.
