### ISSUE TITLE
DAGMC-MCNP6 MCNP6.2 compiler

### ISSUE THREAD

**Issue by haeginh** [svalinn/DAGMC#633]
Hi, I am a novice user, and trying to compile DAGMC-MCNP6 with MCNP6.2.
I have just followed the instructions you provided, and failed to compile.
One think I have changed was the line below. Instead of 
cp -r <path_to_dvd>/MCNP6/Source .
I used
cp -r <path_to_dvd>/MCNP_CODE/MCNP620/Source .
since I could not find Source directory in the suggested location.
However, while 'make' the error message (see below) was printed and just stopped.
Is there any possible reason for this?

/data/home/hhg/dagmc_bld/DAGMC/src/mcnp/mcnp6/Source/import/laqmod31.F90:41114.34:

      use mcnp_random, only : rang
                                  1
/data/home/hhg/dagmc_bld/DAGMC/src/mcnp/mcnp6/Source/import/laqmod31.F90:41113.50:

      implicit real(dknd) (a-h,o-z), integer (i-n)
                                                  2
Error: USE statement at (1) cannot follow IMPLICIT statement at (2)
/data/home/hhg/dagmc_bld/DAGMC/src/mcnp/mcnp6/Source/import/laqmod31.F90:41155.34:

      use mcnp_random, only : rang
                                  1
/data/home/hhg/dagmc_bld/DAGMC/src/mcnp/mcnp6/Source/import/laqmod31.F90:41154.50:

      implicit real(dknd) (a-h,o-z), integer (i-n)
                                                  2
Error: USE statement at (1) cannot follow IMPLICIT statement at (2)
/data/home/hhg/dagmc_bld/DAGMC/src/mcnp/mcnp6/Source/import/laqmod31.F90:42270.34:

      use mcnp_random, only : rang
                                  1
/data/home/hhg/dagmc_bld/DAGMC/src/mcnp/mcnp6/Source/import/laqmod31.F90:42269.50:

      implicit real(dknd) (a-h,o-z), integer (i-n)

**Comment by ljacobson64** [comment]
Are you sure the patch was successfully applied? The patch is supposed to remove all those instances of `use mcnp_random, only : rang`.

**Comment by haeginh** [comment]
Thank you. I have tried the installation carefully by following the instructions one by one, and faced these warning messages again :-(
[ 20%] Building Fortran object src/mcnp/mcnp6/CMakeFiles/mcnp6.dir/Source/src/fmesh_mod.F90.o
/home/hhg/dagmc_bld/DAGMC/src/src/mcnp/mcnp6/Source/src/fmesh_mod.F90:220.54:

    subroutine dagmc_fmesh_get_error_data( fm_id, fref ) bind(c)
                                                      1
Error: Variable 'fref' at (1) cannot have the POINTER attribute because procedure 'dagmc_fmesh_get_error_data' is BIND(C)
/home/hhg/dagmc_bld/DAGMC/src/src/mcnp/mcnp6/Source/src/fmesh_mod.F90:226.56:

    subroutine dagmc_fmesh_get_scratch_data( fm_id, fref ) bind(c)
                                                        1
Error: Variable 'fref' at (1) cannot have the POINTER attribute because procedure 'dagmc_fmesh_get_scratch_data' is BIND(C)
/home/hhg/dagmc_bld/DAGMC/src/src/mcnp/mcnp6/Source/src/fmesh_mod.F90:212.54:

    subroutine dagmc_fmesh_get_tally_data( fm_id, fref ) bind(c)
                                                      1
Error: Variable 'fref' at (1) cannot have the POINTER attribute because procedure 'dagmc_fmesh_get_tally_data' is BIND(C)
/home/hhg/dagmc_bld/DAGMC/src/src/mcnp/mcnp6/Source/src/fmesh_mod.F90:239.45:

  subroutine dagmc_make_fortran_pointer( fref, carray, size ) bind(c)
                                             1
Error: Variable 'fref' at (1) cannot have the POINTER attribute because procedure 'dagmc_make_fortran_pointer' is BIND(C)
make[2]: *** [src/mcnp/mcnp6/CMakeFiles/mcnp6.dir/Source/src/fmesh_mod.F90.o] Error 1
make[1]: *** [src/mcnp/mcnp6/CMakeFiles/mcnp6.dir/all] Error 2

**Comment by ljacobson64** [comment]
This error is known to occur if you try to build DAGMC with gcc-4.8. What compiler are you using? If it's gcc-4.8, can you use a newer compiler?

**Comment by haeginh** [comment]
This solved the problem!! Thank you very much!
