### ISSUE TITLE
Overlap Check Tool

### ISSUE THREAD

**Issue by pshriwise** [svalinn/DAGMC#639]
Someone at the DagMC workshop in Madison mentioned an overlap check tool for discretized DAGMC models. I'm in the process of polishing up a version of this now - just need to add tests. I'm creating this issue to avoid work duplication and make everyone aware of the method I intend to use. 

First, the tool will check all vertices of the problem for containment by more than one volume. My plan is that this will be the default mode. Optionally, users can provide a certain number of points to check along each triangle edge as well. While more thorough, this takes quite a bit of extra time - hence it being an optional approach. Output from the program will make users aware of this option if it is not enabled, as checking the edges of the triangles will make the search more robust.

My thinking on triangle edges is that as the number of points we check on the edges approaches infinity, we should find all overlap (to within machine precision) - i.e. points in the middle of the triangle shouldn't matter because the extent and orientation of the triangle is defined by its edges. I could definitely be missing something there though, so please let me know if there's something more I should look into.

**Comment by pshriwise** [comment]
Related issue: #629

**Comment by gonuke** [comment]
resolved by #641
