### ISSUE TITLE
AStyle shipping with DAGMC

### ISSUE THREAD

**Issue by makeclean** [svalinn/DAGMC#640]
We used to ship astyle with DAGMC for user convenience, the requirement of style added an additional burden to DAGMC development which was already seen as quite off putting. It came with an added bonus that the wild west of package manager distributed versions of astyle was skipped an developers were guarenteed a single version. It seems with evidence from the past week that the decision to stop distributing a fixed version of astyle was incorrect and we need to ship it again. This can be done in a number of ways, we do what we did before which was to wholesale bring in the code via a git pull, or we could more elegently do a git external_dependecy add either way I think we should ship with this.

**Comment by gonuke** [comment]
I seem to remember that it was essentially equivalent problems regarding compatibility with CI that caused us to stop shipping astyle.

Maybe we need a similar style checker that is less fragile to OS versions?

**Comment by makeclean** [comment]
I dont see how that could possibly be the case? I remember that people weren't using the same command in astyle, which differed from that in the website. But yes, either reinstate astyle with correct documentation or less fragile style checker as you say.

________________________________________

**Comment by gonuke** [comment]
deprecated by switching to `clang-format` and continuing reservations about shipping a standard product...
