### ISSUE TITLE
Update source directories containing binary targets

### ISSUE THREAD

**Issue by pshriwise** [svalinn/DAGMC#644]
In #641, it was suggested that our `src/*/build` containing binaries installed with DAGMC be updated to something that wouldn't overlap with potential build directory names.

**Comment by pshriwise** [comment]
Or perhaps removed in and placed in `src/*` with tests in `src/*/tests` as mentioned [here](https://github.com/svalinn/DAGMC/pull/641#discussion_r334988022)

**Comment by ljacobson64** [comment]
Addressed by #645
