### ISSUE TITLE
Automatic graveyard generation

### ISSUE THREAD

**Issue by pshriwise** [svalinn/DAGMC#649]
Graveyards can be problematic when working with DAGMC geometries (particularly for viz), but are necessary to robustly determine particle termination in DAGMC simulations. The graveyard volume can be automatically generated at runtime in a DAGMC simulation if a graveyard volume is not already present.

A rectangular shell prism can then be generated that is just larger than the size of the model.

A start for something like this can be found [here](https://github.com/pshriwise/openmc/blob/9ef18f79ed3176a1dd9d487f6ca240fe430c2d68/src/cad.cpp#L9).

**Comment by shimwell** [comment]
Might be best to this without Trelis / Cubit so that users of the PPP + OCC_faceter workflow can also get the automatic graveyard

**Comment by pshriwise** [comment]
For sure! This would be done entirely in MOAB, manually setting up a volume using the typical DAGMC conventions.
