### ISSUE TITLE
mcnp5.mpi segfaults with built with gfortran on Ubuntu

### ISSUE THREAD

**Issue by ljacobson64** [svalinn/DAGMC#661]
If you build native MCNP or DAG-MCNP with the following things being true:

* MCNP version: 5
* MPI enabled: yes
* Fortran compiler: gfortran
* Linux distro: Ubuntu

then the executable segfaults, without fail. If any of those 4 things are changed (i.e. MCNP6, or no MPI support, or Intel fortran, or some other distro), then the executable works.

This is not a new issue. This has been happening for years, but I don't know why.

And just to clarify, this bug occurs in both native MCNP5 and DAG-MCNP5.

**Comment by gonuke** [comment]
Is this documented by LANL? Is this our problem?

**Comment by gonuke** [comment]
Does this persist @ljacobson64? Do we care?

**Comment by ljacobson64** [comment]
Just tested this -- I don't think this is our problem. I get the segfault in the native version of `mcnp5.mpi`. Going to close this issue.
