### ISSUE TITLE
Shared library testing on CI and Geant4

### ISSUE THREAD

**Issue by pshriwise** [svalinn/DAGMC#673]
So I noticed recently that:

  1. We don't do testing on executables linked to our shared libraries in CI 
  2. When shared testing is enabled, the dagsolid_unit_tests test fails to find some of the libraries it needs and fails on Ubuntu 18.04 only

After some digging, I found that this is because in our 16.04 builds the `RPATH` property of shared libraries and executables is set whereas in 18.04 the `RUNPATH` property is set. This difference is expected as the linking program in Ubuntu, `ld`, moved to using `RUNPATH` in 18.04. (Some links on the difference between these properties and their effects on how libraries are dynamically loaded are at the bottom of this long-winded issue.)

The important difference here is that the `RUNPATH` property won't dynamically load transitive libraries while `RPATH` will. None of the Geant4 libraries have their own `RPATH`/`RUNPATH` properties set -- at least for the installation we rely on in CI anyway. As a result, the libraries, executables, and tests related to Geant4 fail find their dependencies at runtime. Specifically, the problem we run into first is that we link to the `libG5geometry.so` library which in turn links to the `libG4graphics_reps.so` library. These two are in the same location, but because of the `RUNPATH` limitation `libG4graphics_rps.so` isn't found.

I see a couple of options to solve this problem:

__Option 1:__

The Geant4 team seems to be aware that a user's environment needs to be modified to work correctly with their installation and provide a `geant4.sh` in the installation `bin` directory to fix that issue. If we want to count on Geant4 user experience, we can expect that they'll know to source this file before using any of the executables/libraries we produce and things should work just fine. Then we can source this file as part of our test environment or add the Geant4 `lib` directory to the `LD_LIBRARY_PATH` for the test and call it good.

__Option 2:__

Ensure that `RPATH` is set instead of `RUNPATH`. This can be done by adding `--disable-new-dtags` to the CMake shared linker flags in the `/src/geant4/` directory which should affect only the targets build in that space.

I'm leaning toward option 1 and have solution in place, but I'd thought I'd explain the problem here and see what others think.

Info on `RPATH` vs. `RUNPATH`:

  - https://gitlab.kitware.com/cmake/community/-/wikis/doc/cmake/RPATH-handling
  - https://medium.com/nataraj-raghavendra/rpath-vs-runpath-883029b17c45

**Comment by ljacobson64** [comment]
I suspect this issue can be solved by adding

```-DCMAKE_INSTALL_RPATH=${geant4_install_dir}/lib```

to the cmake config we use when configuring Geant4 in the Docker image

**Comment by pshriwise** [comment]
That's a good option too! I'll try that out and see how it goes.

**Comment by pshriwise** [comment]
That seems to do the trick. I'll make a PR with changes to enabled shared library testing and include this addition to our Geant4 build script.

CI will fail at first but I'll update the docker image and then hopefully we'll see it succeed.

**Comment by ljacobson64** [comment]
Sounds good

**Comment by ahnaf-tahmid-chowdhury** [comment]
Fixed by #674
