### ISSUE TITLE
Move PyNE to a submodule and amalgamate at build-time

### ISSUE THREAD

**Issue by gonuke** [svalinn/DAGMC#730]
We currently update PyNE as amalgamated source within DAGMC.  This requires a special manual process and PR that is difficult to review.

As an alternative, we can add PyNE as a submodule and at build time, either run the amalgamation, or (per @pshriwise) build the C++ in place with the AMALGAMATE flag set.

**Comment by pshriwise** [comment]
Addressed by #731
