### ISSUE TITLE
random OverlappingVolumesTest.test1 fail

### ISSUE THREAD

**Issue by bam241** [svalinn/DAGMC#732]
we seem to have a random fail on:
```[ RUN      ] OverlappingVolumesTest.test1

/root/build_dir/DAGMC/src/overlap_check/test/overlap_check_test.cpp:38: Failure
Value of: 1
Expected: olaps.size()
Which is: 2
[  FAILED  ] OverlappingVolumesTest.test1 (2304 ms)
```

I saw it fail twice, on different build configuration:
https://app.circleci.com/pipelines/github/svalinn/DAGMC/350/workflows/f9b1ebd1-7e85-45ea-aa88-32bf06ea9354/jobs/1334
https://app.circleci.com/pipelines/github/svalinn/DAGMC/350/workflows/8f228010-e483-4bb5-b910-de93d9a9b661/jobs/1332

rerun seems to fix them...

**Comment by bam241** [comment]
they all work on the last rerun:
https://app.circleci.com/pipelines/github/svalinn/DAGMC/350/workflows/87941772-ad7d-4aab-b8e2-1ae530987372

**Comment by pshriwise** [comment]
Thanks for creating an issue for this. For the record books, we first identified the problem with this test in #728 as a problem with thread safety in MOAB. A PR has been opened there with a fix.

**Comment by gonuke** [comment]
This seems to have been resolved by MOAB updates
