### ISSUE TITLE
Add double-down job to CI for pull requests

### ISSUE THREAD

**Issue by pshriwise** [svalinn/DAGMC#733]
I'm hoping to do a release of this package in the near future and word is that double-down is being used with DAGMC more frequently in the wild. As a result, I'll propose that we add it to CI to test PRs into DAGMC. This will avoid reactionary fixes in `double-down`/`DAGMC` to broken builds in the `develop` branch after merging. One example of this could have happened with #714 if I hadn't happened to test it with `double-down` locally.

I think I originally suggested that we only test `double-down` on merges to `develop` to mimic the experimental build functionality of Travis that is unavailable in CI, but I think that was a mistake for the reasons above.

**Comment by gonuke** [comment]
Resolved by #738
