### ISSUE TITLE
Dockerfiles for CI undermine benefits of docker

### ISSUE THREAD

**Issue by gonuke** [svalinn/DAGMC#737]
It appears that when the dockerfiles rely on scripts to perform the bulk of the work of installation, they are not able to correctly judge whether or not that docker build command matches previous attempts to run that command.  This causes unnecessary rebuilds of docker images, particularly egregious when the Geant4 build takes so long.

Recognizing that the current scheme was designed carefully in its current form, it may not be serving us well.

**Comment by ahnaf-tahmid-chowdhury** [comment]
I think this issue is already fixed as we are using multi-stage docker builds and all the script commands are available in the Dockerfile.

**Comment by gonuke** [comment]
This was resolved by a series of CI improvements
