### ISSUE TITLE
Streamline dependencies of docker CI images

### ISSUE THREAD

**Issue by gonuke** [svalinn/DAGMC#750]
A review of the the dependencies, esp. apt-get and pip, that are included for CI images in order to minimize the size and communicate the true dependency list.

The current CI docker images install some libraries that may no longer be necessary (e.g. BLAS/LAPACK).

**Comment by ahnaf-tahmid-chowdhury** [comment]
Still it's an issue?

**Comment by gonuke** [comment]
I think it is an issue. For example, we install HDF5 libraries even though we build our own HDF5 every time (unless we pursue #608).  It would be great to remove any packages we don't need.  This would probably be a matter of manually testing our Dockerfile with individual packages removed and see if it works, one at a time.

**Comment by ahnaf-tahmid-chowdhury** [comment]
To work on this, we need to enable all of the options. BUILD_MCNP5 or BUILD_MCNP6, BUILD_MCNP_PLOT, BUILD_MCNP_OPENMP, BUILD_MCNP_MPI, BUILD_MCNP_PYNE_SOURCE, BUILD_STATIC_LIBS, BUILD_STATIC_EXE, BUILD_PIC, BUILD_FLUKA, DOUBLE_DOWN, BUILD_CI_TESTS are needed to be turned on.

I have noticed #677 is working on FLUKA build.
