### ISSUE TITLE
Housekeeping test may not be correct, but not causing errors

### ISSUE THREAD

**Issue by gonuke** [svalinn/DAGMC#775]
**Describe the Bug**<br/>
The housekeeping test should run `clang-format` but there appears to be an error finding it.

**To Reproduce**<br/>
All PR's will launch the Housekeeping test.  Here is [one example](https://github.com/svalinn/DAGMC/pull/727/checks?check_run_id=3146406659) (expand the "Housekeeping" job on the right).

The script runs `find` and passes results through `clang-format`.  When it doesn't find it, it reports an error but also does not produce any output that is later checked for pass/fail.

**Expected Behavior**<br/>
The `find` command should function correctly and possibly generate output.

![clang-format](https://user-images.githubusercontent.com/764326/126830621-d01c5a41-0a3a-452f-829b-67d36230967b.png)

**Comment by pshriwise** [comment]
Addressed in #776
