### ISSUE TITLE
Broken link on the project page: https://svalinn.github.com/DAGMC

### ISSUE THREAD

**Issue by yurivict** [svalinn/DAGMC#782]

**Comment by pshriwise** [comment]
Hi @yurivict. Nice to meet you and thanks for reporting this! I'm assuming you're referring to the link on the github homepage in the image below, but I wanted to double-check w/ you that you didn't see it somewhere else as well.

![bitmap](https://user-images.githubusercontent.com/4563941/136779053-070d1794-6aed-4e6e-a508-8d60531d8371.png)

@gonuke, @makeclean I went ahead and updated that link to https://svalinn.github.io/DAGMC. Please let me know if we should correct it another way.

**Comment by yurivict** [comment]
Yes, this is the link.

**Comment by pshriwise** [comment]
Excellent. Thanks for confirming. I'm going to go ahead and mark this as resolved.
