### ISSUE TITLE
Cannot find source file: .../src/pyne/pyne.cpp

### ISSUE THREAD

**Issue by yurivict** [svalinn/DAGMC#783]
rev. 472ac87 fails like this when being configured with ```-DBUILD_STATIC_LIBS=OFF -DBUILD_TESTS=OFF```

Git submodule is present but it doesn't contain ```pyne.cpp```.

OS: FreeBSD 13

**Comment by pshriwise** [comment]
Any updates on this @yurivict? I haven't had time to look into it yet.

**Comment by gonuke** [comment]
This may be related to the problem I'm working on the propagating PyNE versions

**Comment by bam241** [comment]
It might be a amalgamation problem.
I'd check if you don't get a python error in the CMake output or an error about the amalgamation....

**Comment by yurivict** [comment]
> Any updates on this @yurivict?

The error is still present in the current master branch:
```
-- Configuring done
CMake Error at cmake/DAGMC_macros.cmake:228 (add_library):
  Cannot find source file:

    /disk-samsung/freebsd-ports/science/dagmc/work/DAGMC-3fd335e/src/pyne/pyne.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc
Call Stack (most recent call first):
  src/pyne/CMakeLists.txt:36 (dagmc_install_library)


CMake Error at cmake/DAGMC_macros.cmake:228 (add_library):
  No SOURCES given to target: pyne_dagmc-shared
Call Stack (most recent call first):
  src/pyne/CMakeLists.txt:36 (dagmc_install_library)
```

The code does refer to ```pyne.cpp``` (please grep for it), but it doesn't contain ```pyne.cpp```.

**Comment by gonuke** [comment]
Do you also get a message about "PyNE AMALGAMATION" earlier in the CMake process?

**Comment by yurivict** [comment]
Yes:
> -- PyNE AMALGAMATION FAILED: No such file or directory

**Comment by yurivict** [comment]
There is a bug in ```src/pyne/amalgamate_pyne.sh```: bash is not at /bin/bash. This line should be:
```#!/usr/bin/env bash```

All *.sh files having this problem should be fixed.
