### ISSUE TITLE
Is it possible to build DAGMC with Salome or other solution instead of Cubit?

### ISSUE THREAD

**Issue by ParticleTruthSeeker** [svalinn/DAGMC#791]
**Is your feature request related to an enhancement? Please describe.**<br/>
A clear and concise description of what change you would like to see.

**Is your feature request related to a problem? Please describe.**<br/>
A clear and concise description of what the problem is.

**Describe the solution or outcome you'd like.**<br/>

**Describe alternatives you've considered.**<br/>

**Additional Context**<br/>

**Comment by makeclean** [comment]
Whilst you can create your geometries using Salome, exporting to STEP when you have the geometry complete. The final 'markup' and export of the geometry for being ready to run can only be done in Cubit right now. Of course, Cubit now offers a free academic version, assuming you're doing research, then you can use the Cubit-DAGMC workflow without issue. 

Philosophically, DAGMC geometry conform to a particular set of expectations so it should be possible to do it from Salome, we just haven't had any efforts in that particular direction to date.

**Comment by ParticleTruthSeeker** [comment]
Hi! Thank you for the reply. I have followed some of the materials you presented where you mentioned some efforts are being made in this regard.
What kind of efforts would be required on the Salome front if you don't mind me asking? A PhD effort from KIT resulted in Salome MCCAD. Would an analogous effort be required to do this with DAGMC?

https://openmc.discourse.group/t/trelis-or-cubit/710/2
In this thread the STL workflow is mentioned but it doesn't go into any further implementation details. Is this documented somewhere else?

**Comment by makeclean** [comment]
Yeah, its not a fully recommended workflow to my knowledge because its so caveated in terms of application, for example if you have geometrically coindicent surfaces, then you can have transport errors due to important missing information. I would ask @pshriwise to comment as I think he is the author?

In order to support SALOME, I guess it would need a similar effort to McCAD, but I question if it would academically lead to a PhD? We do have some work in progress on producing DAGMC geometries using a fully open source stack, but its at an early stage.

**Comment by pshriwise** [comment]
Hi @ParticleTruthSeeker. Love the name. The STL workflow is a possibility, yes. @shimwell has put together a Python package that will combine the STL files for you and apply material assignments based on a JSON file that links the individual STL files to the material assignments. However, as @makeclean mentioned, this requires that the STL files do not touch and do not overlap for successful transport in DAGMC. This works well for some applications like the parametric studies @shimwell is interested in, but it can remove the helpfulness of many CAD features -- even subtracting volumes can leave you with coincident surfaces that would be problematic in that workflow.

**Comment by shimwell** [comment]
Here is a link, watch out for overlaps
https://github.com/fusion-energy/stl_to_h5m

I also use a cubit based one
https://github.com/fusion-energy/cad_to_h5m

**Comment by ParticleTruthSeeker** [comment]
Wow thank you for all your responses. 
Andrew) That is great. I only mentioned the PhD to gauge the amount of work required and how far away this is from being implemented. If your project is online I will look out for it. 

Patrick) Haha thank you. I wasn't sure what to name myself so I took inspiration from a project I was working on to simulate scattering in a nano material. I understand the stl limitation, however it was my impression that ultimately we are working with meshes and that several open source implementations exist to heal those. Additionally would placing each sub mesh of a larger component in a global mesh defined as a vacuum or atmospheric gas resolve the problem? 
I think the main motivation for me would be to use this framework to couple directly the heating from radiation in a material and work out the cooling requirements. I was thinking of using Code-Aster hence the Salome thought, while I also came across the  SMITER framework which is very interesting and has a similar motivation though of course with a specific application in mind.  At this stage my geometry is pretty simple and I could get away with duplicate geometries but I am interested in this work notwithstanding.

Jonathan) Thank you for the links. Would the first allow one to completely bypass cubit? 
I also came across paramak and the breeder blanket model maker and associated publication. Its very interesting and I look forward to exploring the code. I watched Dennis Whyte's presentation and I was excited to find an open source framework exploring the topic.
I just wanted to say I admire the work you all do and I hope to be able to contribute at some point as well.

**Comment by makeclean** [comment]
Well if it helps for the heating part, we've been working on https://github.com/aurora-multiphysics/aurora - for the exact purpose you mention, determining how much cooling you need for a given nuclear heat load - its MOOSE based, with OpenMC + DAGMC for the radiation transport. 

"I understand the stl limitation, however it was my impression that ultimately we are working with meshes and that several open source implementations exist to heal those. Additionally would placing each sub mesh of a larger component in a global mesh defined as a vacuum or atmospheric gas resolve the problem?"

If you can truely embed them with the appropriate geometry/topology information and your geometry had no overlaps, then yes that would likely be fine. However, we already have this capability with DAGMC called the 'implicit complement' which defines the remaining space, this is in fact exactly how the current capability using STL effectively works. The real issue which stymies this simplistic workflow is the issues we face when tracking the geometries with overlaps; which can lead to pathological particle tunneling (wrong results). There are enough oddities that happen when you have coincidence surfaces which are faceted at different resolutions (which is implicit when using STL based workflows with no 'imprinting and merging'). Further, there are issues when doing Boolean operations on triangle surface meshes, meaning that you *must* use arbitrary precision arithmetic, which implies the use of something like CGAL, which I've had some success with, then you can explicitly determine the overlap and resolve it, but there are still edge cases (which are actually quite common) that lead to a really poor level of automation. 

STL overall is a really poor choice of format; poor metadata quality, low numerical precision. A better choice would be 3MF which can contain metadata, has a much higher numerical precision, we could support quite a lot of DAGMC intrinsic metadata with 3MF.

**Comment by shimwell** [comment]
@ParticleTruthSeeker yes the [stl-to-h5m](https://github.com/fusion-energy/stl_to_h5m) package does let one completely by pass cubit provided that you have non overlapping or touching geometry. This is not ideal but can be handy for some use cases. Patrick is the brains behind that package, I just refactored his original [gist](https://gist.github.com/pshriwise/52452c37d4b7dd89bdc9374e13c35157) and did the pypi packaging, testing docs and simple stuff.

On a related topic, you can check for overlaps with DAGMC. https://github.com/fusion-energy/stl_to_h5m#usage---checking-for-overlaps

Glad to hear you have come across a few of the tools. Most of the them are in [this ever expanding diagram](https://github.com/fusion-energy/fusion_neutronics_workflow).

We could do with an improved geometry to h5m convertor. I keep meaning to have a go at the gmesh route @makeclean found and I am also aware of a VTK route that others use. If you have any luck with Salome then keep us posted.

If you can give me a few pointers on the gmesh route then I can write up a package to try out @makeclean

**Comment by makeclean** [comment]
@shimwell is that overlap check tool distinct from the DAGMC overlap tool?

**Comment by shimwell** [comment]
Yes the link has a few words on how to install and use the DAGMC overlap tool

### Usage - checking for overlaps

To check for overlaps in the resulting h5m file one can use the DAGMC overlap checker. -p is the number of points to check on each line
```
conda install -c conda-forge dagmc
overlap_check dagmc.h5m -p 1000
```

**Comment by makeclean** [comment]
So its a completely separate implementation than https://github.com/svalinn/DAGMC/tree/develop/src/overlap_check? Using none of the same code?

**Comment by shimwell** [comment]
I have not made a new overlap checker. I am just directing users to the DAGMC overlap checker. Yes it is the same one in your link. I was not aware of any others.

**Comment by makeclean** [comment]
Ah, sorry its was the conda stuff that confused me :-) I'd presumed they had it install so only needed the `overlap_check` part

**Comment by shimwell** [comment]
Yep I believe the conda distribution of the overlap tool is fairly recent.

I would be interested in your thoughts on this approach of removing overlapping faces
https://github.com/mikedh/trimesh/issues/857

**Comment by makeclean** [comment]
What that seems to be doing (happy to be corrected) is removing overlapping-coplanar triangles on the same surface, such that you get back a fresh triangulation which does not overlap. This is distinct from the topological problem we have with the STL based workflow regarding two differently faceted surfaces.

**Comment by pshriwise** [comment]
This conversation seems to have fizzled out. I'm hoping that @ParticleTruthSeeker got what they needed here. Feel free to re-open this issue if not!
