### ISSUE TITLE
Making use of DAGMC in python package

### ISSUE THREAD

**Issue by shimwell** [svalinn/DAGMC#806]
**Describe the Bug**<br/>
Hi all, I'm making some progress with writing a python package using pybind11 that makes use of DAGMC. I'm getting a small compile error at the moment due to the file names in DAGMC.

This line looks for DagMCVersion.hpp https://github.com/svalinn/DAGMC/blob/50caabf16b12179f92e71d4dcfb5bf6090b30cb6/src/dagmc/DagMC.hpp#L13

The filename in the repo is ``` DagMCVersion.hpp.in``` https://github.com/svalinn/DAGMC/tree/develop/src/dagmc

So my package doesn't find the file when being built with conda.

I guess we control the version number using [this](https://github.com/svalinn/DAGMC/blob/50caabf16b12179f92e71d4dcfb5bf6090b30cb6/src/dagmc/CMakeLists.txt#L7) line in the cmake but I'm not sure if conda can pass a variable in here

The package is currently finding ```#include "dagmc/DagMC.hpp"``` but then the ```DagMC.hpp``` has an include for the ```DagMCVersion.hpp``` which it does not find. I believe this is due to the filename ending in ```.in``` and the conda package creation not setting the version number or building DAGMC to make the ```.hpp``` file.

Any ideas to get this working appreciated.

![Screenshot from 2022-05-17 15-45-07](https://user-images.githubusercontent.com/8583900/168839997-76e8d738-5015-4b56-95a6-4c6889a4ea70.png)

**To Reproduce**<br/>
from a conda environment`
```bash
conda install conda-build
git clone https://github.com/shimwell/pybind11_python_example.git
cd pybind11_python_example
conda install -c conda-forge mamba
mamba build conda
```

The resulting compressed file can then be installed with, but I've not got this far
``` mamba install -c path_to_file dagmc_volume_finder```

**Expected Behavior**<br/>
python package gets made that can make use of DAGMC C++ code

**Screenshots or Code Snippets**<br/>
If applicable, add screenshots or snippets of code and error messages to help explain your problem.
Note, please do not include screenshots or snippets of code that is export controlled.

**Please complete the following information regarding your system:**<br/>
ubuntu

**Additional Context**<br/>
This error can be observed with the CI https://github.com/shimwell/pybind11_python_example/runs/6472883702?check_suite_focus=true

**Comment by shimwell** [comment]
I've added this[ version file to a DAGMC fork ](https://github.com/shimwell/DAGMC/blob/adding_version_file/src/dagmc/DagMCVersion.hpp)and this has helped progress beyond the error I was seeing.

I've also[ included MOAB ](https://github.com/shimwell/pybind11_python_example/blob/009a06b7dee5fc49f026f61493a9c4083ed52eaf/conda/meta.yaml#L12-L17)in the meta.yaml as the package was looking for .hpp files from MOAB as well. I've also added some extra paths to the[ include dir ](https://github.com/shimwell/pybind11_python_example/blob/009a06b7dee5fc49f026f61493a9c4083ed52eaf/setup.py#L73-L75)in the setup.py to find some moab files that are needed

Currently stuck on this error ```fatal error: moab/MOABConfig.h: No such file or directory```

**Comment by ahnaf-tahmid-chowdhury** [comment]
Did you have tried with

```
setup(
    include_dirs=['/path/to/moab/include'],
)
```

I think we can fix that by adding include dir.

However, the workflow is expaired. Can we plan this and move this in [PyDAGMC](https://github.com/svalinn/pydagmc)?

**Comment by gonuke** [comment]
I'm not sure I follow what you are trying to do.  Conceptually, DAGMC will need to be built at some point before this, or during this, right?  The build process for DAGMC should create this file.

**Comment by gonuke** [comment]
I didn't realize how old this was on my last comment - is this still relevant @shimwell ?  If not, please feel free to close.

**Comment by shimwell** [comment]
If we manage to move to a pypi distrbuted pip install for openmc then I think we would need something like this on the dagmc to include dagmc within the openmc wheel. We can close this as until we have that openmc pypi distribution we won't need a dagmc one
