### ISSUE TITLE
UWUW Unit Test Failure

### ISSUE THREAD

**Issue by pshriwise** [svalinn/DAGMC#824]
I've got some UWUW unit tests failing in a build on a Ubuntu machine (gcc 9.4.0, CMake 3.23.2). It seems like something is up with the tests' ability to find the test files?

```shell
The following tests FAILED:
          6 - uwuw_unit_tests (Subprocess aborted)
          8 - uwuw_unit_tests_preprocessor (Failed)
Errors while running CTest
Output from these tests are in: /home/pshriwise/aurora_build/dagmc/bld/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
make: *** [Makefile:71: test] Error 8
```

## uwuw_unit_tests_preprocessor

When run from my build directory the output of `uwuw_unit_tests_preprocessor` is: 

```shell
[==========] Running 12 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 10 tests from UWUWTest
[ RUN      ] UWUWTest.SetUp
[       OK ] UWUWTest.SetUp (0 ms)
[ RUN      ] UWUWTest.name8
[       OK ] UWUWTest.name8 (0 ms)
[ RUN      ] UWUWTest.name8RemoveSpace
[       OK ] UWUWTest.name8RemoveSpace (0 ms)
[ RUN      ] UWUWTest.name8RemoveCommaAndSpace
[       OK ] UWUWTest.name8RemoveCommaAndSpace (0 ms)
[ RUN      ] UWUWTest.name8IncrementID
[       OK ] UWUWTest.name8IncrementID (0 ms)
[ RUN      ] UWUWTest.name8lessthan8
[       OK ] UWUWTest.name8lessthan8 (0 ms)
[ RUN      ] UWUWTest.name8lessthan8preserve
[       OK ] UWUWTest.name8lessthan8preserve (0 ms)
[ RUN      ] UWUWTest.name8lessthan8preserve100
[       OK ] UWUWTest.name8lessthan8preserve100 (460 ms)
[ RUN      ] UWUWTest.name8lessthan8preserve1000Steel
[       OK ] UWUWTest.name8lessthan8preserve1000Steel (352 ms)
[ RUN      ] UWUWTest.materialMetadata
Using the DOUBLE-DOWN interface to Embree.
unknown file: Failure
C++ exception with description "File not found: mat_lib.h5" thrown in the test body.
[  FAILED  ] UWUWTest.materialMetadata (1 ms)
[----------] 10 tests from UWUWTest (815 ms total)

[----------] 2 tests from UWUWPreprocTest
[ RUN      ] UWUWPreprocTest.testMaterials
Using the DOUBLE-DOWN interface to Embree.
unknown file: Failure
C++ exception with description "File not found: mat_lib.h5" thrown in SetUp().
[1]    396267 segmentation fault (core dumped)  ./src/uwuw/tests/uwuw_unit_tests_preprocessor
```
When run from `src/uwuw/tests` in my build dir, the output of `uwuw_unit_tests_preprocessor` is: 

```shell
[==========] Running 12 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 10 tests from UWUWTest
[ RUN      ] UWUWTest.SetUp
[       OK ] UWUWTest.SetUp (0 ms)
[ RUN      ] UWUWTest.name8
[       OK ] UWUWTest.name8 (0 ms)
[ RUN      ] UWUWTest.name8RemoveSpace
[       OK ] UWUWTest.name8RemoveSpace (0 ms)
[ RUN      ] UWUWTest.name8RemoveCommaAndSpace
[       OK ] UWUWTest.name8RemoveCommaAndSpace (0 ms)
[ RUN      ] UWUWTest.name8IncrementID
[       OK ] UWUWTest.name8IncrementID (0 ms)
[ RUN      ] UWUWTest.name8lessthan8
[       OK ] UWUWTest.name8lessthan8 (0 ms)
[ RUN      ] UWUWTest.name8lessthan8preserve
[       OK ] UWUWTest.name8lessthan8preserve (0 ms)
[ RUN      ] UWUWTest.name8lessthan8preserve100
[       OK ] UWUWTest.name8lessthan8preserve100 (413 ms)
[ RUN      ] UWUWTest.name8lessthan8preserve1000Steel
[       OK ] UWUWTest.name8lessthan8preserve1000Steel (343 ms)
[ RUN      ] UWUWTest.materialMetadata
Using the DOUBLE-DOWN interface to Embree.
Loading file dag_file.h5m
Initializing the GeomQueryTool...
Using faceting tolerance: 0.001
Implicit Complement assumed to be Vacuum
material CentreStack was not found in the material library   
```

## uwuw_unit_tests

When run from the build dir:

```shell
[==========] Running 9 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 9 tests from UWUWTest
[ RUN      ] UWUWTest.SetUp
unknown file: Failure
C++ exception with description "basic_string::_M_construct null not valid" thrown in SetUp().
[  FAILED  ] UWUWTest.SetUp (1 ms)
[ RUN      ] UWUWTest.filepath1
unknown file: Failure
C++ exception with description "basic_string::_M_construct null not valid" thrown in SetUp().
[  FAILED  ] UWUWTest.filepath1 (0 ms)
[ RUN      ] UWUWTest.filepath2
unknown file: Failure
C++ exception with description "basic_string::_M_construct null not valid" thrown in SetUp().
[  FAILED  ] UWUWTest.filepath2 (0 ms)
[ RUN      ] UWUWTest.filepath3
unknown file: Failure
C++ exception with description "basic_string::_M_construct null not valid" thrown in SetUp().
[  FAILED  ] UWUWTest.filepath3 (0 ms)
[ RUN      ] UWUWTest.filepath4
unknown file: Failure
C++ exception with description "basic_string::_M_construct null not valid" thrown in SetUp().
[  FAILED  ] UWUWTest.filepath4 (0 ms)
[ RUN      ] UWUWTest.materiallibrary1
unknown file: Failure
C++ exception with description "basic_string::_M_construct null not valid" thrown in SetUp().
[  FAILED  ] UWUWTest.materiallibrary1 (0 ms)
[ RUN      ] UWUWTest.materiallibrary2
unknown file: Failure
C++ exception with description "basic_string::_M_construct null not valid" thrown in SetUp().
[  FAILED  ] UWUWTest.materiallibrary2 (0 ms)
[ RUN      ] UWUWTest.material_datapath
unknown file: Failure
C++ exception with description "basic_string::_M_construct null not valid" thrown in SetUp().
[  FAILED  ] UWUWTest.material_datapath (0 ms)
[ RUN      ] UWUWTest.mat_write
unknown file: Failure
C++ exception with description "basic_string::_M_construct null not valid" thrown in SetUp().
[  FAILED  ] UWUWTest.mat_write (1 ms)
[----------] 9 tests from UWUWTest (2 ms total)

[----------] Global test environment tear-down
[==========] 9 tests from 1 test case ran. (2 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 9 tests, listed below:
[  FAILED  ] UWUWTest.SetUp
[  FAILED  ] UWUWTest.filepath1
[  FAILED  ] UWUWTest.filepath2
[  FAILED  ] UWUWTest.filepath3
[  FAILED  ] UWUWTest.filepath4
[  FAILED  ] UWUWTest.materiallibrary1
[  FAILED  ] UWUWTest.materiallibrary2
[  FAILED  ] UWUWTest.material_datapath
[  FAILED  ] UWUWTest.mat_write

 9 FAILED TESTS
 ```
 
 When run from the `src/uwuw/tests/` directory it passes.

**Comment by makeclean** [comment]
That's a pretty crusty GCC version, does that reflect an Ubuntu in common use?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Patrick Shriwise ***@***.***>
Sent: Wednesday, August 3, 2022 10:07:58 PM
To: svalinn/DAGMC ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [svalinn/DAGMC] UWUW Unit Test Failure (Issue #824)


I've got some UWUW unit tests failing in a build on a Ubuntu machine (gcc 9.4.0, CMake 3.23.2). It seems like something is up with the tests' ability to find the test files?

The following tests FAILED:
          6 - uwuw_unit_tests (Subprocess aborted)
          8 - uwuw_unit_tests_preprocessor (Failed)
Errors while running CTest
Output from these tests are in: /home/pshriwise/aurora_build/dagmc/bld/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
make: *** [Makefile:71: test] Error 8

uwuw_unit_tests_preprocessor

When run from my build directory the output of uwuw_unit_tests_preprocessor is:

[==========] Running 12 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 10 tests from UWUWTest
[ RUN      ] UWUWTest.SetUp
[       OK ] UWUWTest.SetUp (0 ms)
[ RUN      ] UWUWTest.name8
[       OK ] UWUWTest.name8 (0 ms)
[ RUN      ] UWUWTest.name8RemoveSpace
[       OK ] UWUWTest.name8RemoveSpace (0 ms)
[ RUN      ] UWUWTest.name8RemoveCommaAndSpace
[       OK ] UWUWTest.name8RemoveCommaAndSpace (0 ms)
[ RUN      ] UWUWTest.name8IncrementID
[       OK ] UWUWTest.name8IncrementID (0 ms)
[ RUN      ] UWUWTest.name8lessthan8
[       OK ] UWUWTest.name8lessthan8 (0 ms)
[ RUN      ] UWUWTest.name8lessthan8preserve
[       OK ] UWUWTest.name8lessthan8preserve (0 ms)
[ RUN      ] UWUWTest.name8lessthan8preserve100
[       OK ] UWUWTest.name8lessthan8preserve100 (460 ms)
[ RUN      ] UWUWTest.name8lessthan8preserve1000Steel
[       OK ] UWUWTest.name8lessthan8preserve1000Steel (352 ms)
[ RUN      ] UWUWTest.materialMetadata
Using the DOUBLE-DOWN interface to Embree.
unknown file: Failure
C++ exception with description "File not found: mat_lib.h5" thrown in the test body.
[  FAILED  ] UWUWTest.materialMetadata (1 ms)
[----------] 10 tests from UWUWTest (815 ms total)

[----------] 2 tests from UWUWPreprocTest
[ RUN      ] UWUWPreprocTest.testMaterials
Using the DOUBLE-DOWN interface to Embree.
unknown file: Failure
C++ exception with description "File not found: mat_lib.h5" thrown in SetUp().
[1]    396267 segmentation fault (core dumped)  ./src/uwuw/tests/uwuw_unit_tests_preprocessor

When run from src/uwuw/tests in my build dir, the output of uwuw_unit_tests_preprocessor is:

[==========] Running 12 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 10 tests from UWUWTest
[ RUN      ] UWUWTest.SetUp
[       OK ] UWUWTest.SetUp (0 ms)
[ RUN      ] UWUWTest.name8
[       OK ] UWUWTest.name8 (0 ms)
[ RUN      ] UWUWTest.name8RemoveSpace
[       OK ] UWUWTest.name8RemoveSpace (0 ms)
[ RUN      ] UWUWTest.name8RemoveCommaAndSpace
[       OK ] UWUWTest.name8RemoveCommaAndSpace (0 ms)
[ RUN      ] UWUWTest.name8IncrementID
[       OK ] UWUWTest.name8IncrementID (0 ms)
[ RUN      ] UWUWTest.name8lessthan8
[       OK ] UWUWTest.name8lessthan8 (0 ms)
[ RUN      ] UWUWTest.name8lessthan8preserve
[       OK ] UWUWTest.name8lessthan8preserve (0 ms)
[ RUN      ] UWUWTest.name8lessthan8preserve100
[       OK ] UWUWTest.name8lessthan8preserve100 (413 ms)
[ RUN      ] UWUWTest.name8lessthan8preserve1000Steel
[       OK ] UWUWTest.name8lessthan8preserve1000Steel (343 ms)
[ RUN      ] UWUWTest.materialMetadata
Using the DOUBLE-DOWN interface to Embree.
Loading file dag_file.h5m
Initializing the GeomQueryTool...
Using faceting tolerance: 0.001
Implicit Complement assumed to be Vacuum
material CentreStack was not found in the material library

uwuw_unit_tests

When run from the build dir:

[==========] Running 9 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 9 tests from UWUWTest
[ RUN      ] UWUWTest.SetUp
unknown file: Failure
C++ exception with description "basic_string::_M_construct null not valid" thrown in SetUp().
[  FAILED  ] UWUWTest.SetUp (1 ms)
[ RUN      ] UWUWTest.filepath1
unknown file: Failure
C++ exception with description "basic_string::_M_construct null not valid" thrown in SetUp().
[  FAILED  ] UWUWTest.filepath1 (0 ms)
[ RUN      ] UWUWTest.filepath2
unknown file: Failure
C++ exception with description "basic_string::_M_construct null not valid" thrown in SetUp().
[  FAILED  ] UWUWTest.filepath2 (0 ms)
[ RUN      ] UWUWTest.filepath3
unknown file: Failure
C++ exception with description "basic_string::_M_construct null not valid" thrown in SetUp().
[  FAILED  ] UWUWTest.filepath3 (0 ms)
[ RUN      ] UWUWTest.filepath4
unknown file: Failure
C++ exception with description "basic_string::_M_construct null not valid" thrown in SetUp().
[  FAILED  ] UWUWTest.filepath4 (0 ms)
[ RUN      ] UWUWTest.materiallibrary1
unknown file: Failure
C++ exception with description "basic_string::_M_construct null not valid" thrown in SetUp().
[  FAILED  ] UWUWTest.materiallibrary1 (0 ms)
[ RUN      ] UWUWTest.materiallibrary2
unknown file: Failure
C++ exception with description "basic_string::_M_construct null not valid" thrown in SetUp().
[  FAILED  ] UWUWTest.materiallibrary2 (0 ms)
[ RUN      ] UWUWTest.material_datapath
unknown file: Failure
C++ exception with description "basic_string::_M_construct null not valid" thrown in SetUp().
[  FAILED  ] UWUWTest.material_datapath (0 ms)
[ RUN      ] UWUWTest.mat_write
unknown file: Failure
C++ exception with description "basic_string::_M_construct null not valid" thrown in SetUp().
[  FAILED  ] UWUWTest.mat_write (1 ms)
[----------] 9 tests from UWUWTest (2 ms total)

[----------] Global test environment tear-down
[==========] 9 tests from 1 test case ran. (2 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 9 tests, listed below:
[  FAILED  ] UWUWTest.SetUp
[  FAILED  ] UWUWTest.filepath1
[  FAILED  ] UWUWTest.filepath2
[  FAILED  ] UWUWTest.filepath3
[  FAILED  ] UWUWTest.filepath4
[  FAILED  ] UWUWTest.materiallibrary1
[  FAILED  ] UWUWTest.materiallibrary2
[  FAILED  ] UWUWTest.material_datapath
[  FAILED  ] UWUWTest.mat_write

 9 FAILED TESTS

When run from the src/uwuw/tests/ directory it passes.

**Comment by pshriwise** [comment]
It's just over a year old I think... https://gcc.gnu.org/gcc-9/

This was on a Ubuntu 20.04 installation. 🤷🏻

**Comment by makeclean** [comment]
I've lost all connection to GCC versioning, I'm on 11.2

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ahnaf-tahmid-chowdhury** [comment]
Does the issue still persist?

**Comment by gonuke** [comment]
I guess you can look in recent CI logs to see.  I would guess there are three options: 
1. it passes (this issue can be closed)
2. it fails (but we'd probably know)
3. it is turned off (we should try turning it back on)

**Comment by ahnaf-tahmid-chowdhury** [comment]
Tests are passing with GCC 11. [Log]( https://github.com/svalinn/DAGMC/actions/runs/7776961874/job/21204720316#step:5:20)

**Comment by gonuke** [comment]
I'll invite @pshriwise to close this
