### ISSUE TITLE
DBUILD_MW_REG_TESTS requires h5m models that can't be found as URL missing

### ISSUE THREAD

**Issue by shimwell** [svalinn/DAGMC#858]
**Describe the Bug**<br/>
The CI has a variable called ```DBUILD_MW_REG_TESTS``` which is if set will trigger the downloading of a  tar.gz file containing some h5m geometries from a URL. Unfortunately it looks like the URL used by the wget command has been lost in in the CI transition from travis-ci to circle-ci. I understand that these models are large and the tests are lengthy hence it was an optional test. It looks like we have accidentally gone on for a while without noticing that these tests were not running any more and this was recently noticed during  #822 

**To Reproduce**<br/>
compile dagmc with the ```DBUILD_MW_REG_TESTS``` variable
```
mkdir build
cd build
cmake .. DBUILD_MW_REG_TESTS=ON
make -j
make install
make test
```
**Expected Behavior**<br/>
tests should pass

**Please complete the following information regarding your system:**<br/>
all OS and MOAB versions

**Additional Context**<br/>
[Link to PR ](https://github.com/svalinn/DAGMC/pull/822#issuecomment-1425724550)where this issue was found and is also discussed

**Comment by gonuke** [comment]
I tagged @pshriwise only because he may actually know where the necessary H5M files are for testing....

**Comment by shimwell** [comment]
Filenames of the missing files

```
class ITERMakeWatertightRegressionTest : public MakeWatertightTest {
 protected:
  virtual void setFilename() { filename = "iter_imprinted.h5m"; };
};

class FNSFMakeWatertightRegressionTest : public MakeWatertightTest {
 protected:
  virtual void setFilename() { filename = "model1_360_1.h5m"; };
};

class BLiteMakeWatertightRegressionTest : public MakeWatertightTest {
 protected:
  virtual void setFilename() { filename = "bllite30matls.h5m"; };
};
```

**Comment by ahnaf-tahmid-chowdhury** [comment]
Is the issue already fixed?

**Comment by shimwell** [comment]
I think this one was never solved. But perhaps not a high priority

**Comment by gonuke** [comment]
I think we lost the files, right @pshriwise ?

**Comment by ahnaf-tahmid-chowdhury** [comment]
Is it possible to recreate the files if they are lost? I am willing to work on that. I need instructions on how to create h5m geometries for this.

**Comment by gonuke** [comment]
These were a set of specific H5M files that were useful for these tests.  It is not as simple as just creating some new H5M files.

**Comment by ahnaf-tahmid-chowdhury** [comment]
Always happy to learn new stuffs. If the creator tells me the process how to make those H5M files for these tests, I will  definitely give that a try.

**Comment by shimwell** [comment]
I think the shape, volume etc of the missing h5m files is lost now.

We can close this one as I think it is impossible to recover these h5m files
