### ISSUE TITLE
Build error 

### ISSUE THREAD

**Issue by Coperbytes** [svalinn/DAGMC#900]
**Describe the Bug**<br/>
While making the build does not find the function find_volumme

**To Reproduce**<br/>
Specify the necessary steps to reproduce the behavior. For example,
supply the cmake command used for building if there is a build error,
or the steps taken when using the DAGMC that produced the error.

**Expected Behavior**<br/>
Should do clean build

**Screenshots or Code Snippets**<br/>
```
/openmc/DAGMC/DAGMC/src/dagmc/DagMC.cpp: In member function ‘moab::ErrorCode moab::DagMC::find_volume(const double*, moab::EntityHandle&, const double*)’:
/openmc/DAGMC/DAGMC/src/dagmc/DagMC.cpp:818:32: error: ‘class double_down::RayTracingInterface’ has no member named ‘find_volume’
  818 |   ErrorCode rval = ray_tracer->find_volume(xyz, volume, uvw);
      |                                ^~~~~~~~~~~
make[2]: *** [src/dagmc/CMakeFiles/dagmc-shared.dir/build.make:76: src/dagmc/CMakeFiles/dagmc-shared.dir/DagMC.cpp.o] Error 1
```

**Please complete the following information regarding your system:**<br/>
 - OS: Ubuntu 22.04
 - MOAB Version: 5.4

**Comment by gonuke** [comment]
Thanks for making an issue about this.  I think @pshriwise and @ebknudsen are working on a fix for this.

**Comment by gonuke** [comment]
In the meantime, if you build DAGMC without Double Down, it should work correctly.

**Comment by ebknudsen** [comment]
@pshriwise fixed this in the develop-branch with this PR: https://github.com/pshriwise/double-down/pull/42. It has however not been merged into the main branch. Did you build double-down from the main branch @Coperbytes? Or use an older build?

**Comment by gonuke** [comment]
I think it's merged but without a release yet...?

**Comment by ebknudsen** [comment]
Nope - it _is_ in develop though. main hasn't been touched for 2 yrs unfortunately. A new release would prob. be a good thing.

**Comment by ebknudsen** [comment]
I mean to say - the fix was merged into the develop-branch, but not into main

**Comment by pshriwise** [comment]
Agreed on the double-down release, @ebknudsen. I'll try to find some time to work on that soon.

**Comment by Coperbytes** [comment]
> I mean to say - the fix was merged into the develop-branch, but not into main

@ebknudsen I used installed scripts from your other repo [openmc_install_scripts](https://github.com/openmsr/openmc_install_scripts/blob/main/Ubuntu_22.04/dagmc-install.sh)

This is the branch that was downloaded from the script 

```
 ~/openmc/DAGMC/DAGMC/ git info

## Remote URLs:

origin	https://github.com/svalinn/DAGMC.git (fetch)
origin	https://github.com/svalinn/DAGMC.git (push)

## Remote Branches:

  origin/HEAD -> origin/develop
  origin/develop

## Local Branches:

* develop

## Submodule(s):

 36a6b4b src/pyne/pyne (0.7.7-34-g36a6b4bf)

## Most Recent Commit:

commit b3e2b132aef7d4bf333af4ee9999c0c2ec752601
Author: Patrick Shriwise 

    Merge pull request #869 from gonuke/doc_review_2023_03

```

**Comment by ebknudsen** [comment]
@Coperbytes Sorry - me bad - I meant which branch of double-down. But if you use the openmc_install_scripts then It ought to have been develop for double-down as well. Which platform are you on?

**Comment by Coperbytes** [comment]
I am installing on Ubuntu 22.04, the double_down-install.sh script has main  instead of develop for installation 

` git clone --single-branch --branch main --depth 1 https://github.com/pshriwise/double-down.git`

by changing to develop branch it fixed the build error, now I have issue in installation of openmc should I close this issue and create new issue in openmc_install_scripts repo?

```
openmc/openmc/tests/cpp_unit_tests/test_file_utils.cpp:2:10: fatal error: catch2/catch_test_macros.hpp: No such file or directory
    2 | #include <catch2/catch_test_macros.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [tests/cpp_unit_tests/CMakeFiles/test_file_utils.dir/build.make:76: tests/cpp_unit_tests/CMakeFiles/test_file_utils.dir/test_file_utils.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:994: tests/cpp_unit_tests/CMakeFiles/test_file_utils.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/home/kp/openmc/openmc/tests/cpp_unit_tests/test_distribution.cpp:3:10: fatal error: catch2/catch_test_macros.hpp: No such file or directory
    3 | #include <catch2/catch_test_macros.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [tests/cpp_unit_tests/CMakeFiles/test_distribution.dir/build.make:76: tests/cpp_unit_tests/CMakeFiles/test_distribution.dir/test_distribution.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:968: tests/cpp_unit_tests/CMakeFiles/test_distribution.dir/all] Error 2
/home/kp/openmc/openmc/tests/cpp_unit_tests/test_tally.cpp:2:10: fatal error: catch2/catch_test_macros.hpp: No such file or directory
    2 | #include <catch2/catch_test_macros.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [tests/cpp_unit_tests/CMakeFiles/test_tally.dir/build.make:76: tests/cpp_unit_tests/CMakeFiles/test_tally.dir/test_tally.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1020: tests/cpp_unit_tests/CMakeFiles/test_tally.dir/all] Error 2
[ 97%] Linking CXX executable bin/openmc
[ 97%] Built target openmc
make: *** [Makefile:146: all] Error 2

```

**Comment by ebknudsen** [comment]
@Coperbytes  please do - that is where it belongs - I'll see if I can't fix that later today
