### ISSUE TITLE
Docker build error

### ISSUE THREAD

**Issue by Itay-max** [svalinn/DAGMC#917]
**Describe the Bug**<br/>
I am currently using the latest version of DAGMC and I was trying to build the docker image inside the CI directory. Alsmost all commands in the dockerfile were running great except for "RUN mkdir -p ${dagmc_build_dir}/build && ..." :
 => ERROR [dagmc 4/4] RUN mkdir -p /root/build_dir/dagmc/build && ...

Looked at the log and found the following CMAKE error:

CMake Error at cmake/DAGMC_macros.cmake:228 (add_library):
2.944   Cannot find source file:
2.944
2.944     /root/build_dir/dagmc/src/pyne/pyne.cpp

**To Reproduce**<br/>
build from repository root directory with command: docker build -t dagmc -f CI/Dockerfile .

**Expected Behavior**<br/>
Building the Image without errors

**Comment by gonuke** [comment]
Thanks for the question.  You'll need to make sure you have checked out the submodule in the `src/pyne/pyne` directory.

You can do this from the root directory of the `DAGMC` repository with:
`git submodule update --init`

I hope that helps.

**Comment by Itay-max** [comment]
Thank you for your reply,
the command you specified is part of the docker commands and it was running successfully:
![image](https://github.com/svalinn/DAGMC/assets/57565534/7230ba21-444b-48e6-9a16-78e3bc9e4f3c)

However the CMAKE error still exists.

**Comment by gonuke** [comment]
Sorry for the delay - are you using the latest release version or the most up-to-date code in the `develop` branch?

We're working on a release and the most up-to-date code is working ok.
