### ISSUE TITLE
Surface has no facets warning

### ISSUE THREAD

**Issue by makeclean** [svalinn/DAGMC#946]
Sometimes surfaces have no facets and we get the warning;
```
WARNING: Surface has no facets
```
It should likely be more helpful and say 
```
WARNING: Surface XXX (entityhandle: blah) has no facets
```

**Comment by ahnaf-tahmid-chowdhury** [comment]
Hello @makeclean, regarding the `WARNING: Surface has no facets` message, this is a common occurrence in the realm of 3D modeling, especially with surfaces or meshes. It can stem from a variety of reasons such as degenerate geometry, erroneous inputs, numerical instability, algorithmic constraints, etc.

Could you kindly provide a detailed outline of the steps you took when encountering this error? This would allow us to offer you more precise assistance.

**Comment by makeclean** [comment]
I know what the error is, I'm suggesting that a more helpful error message would tell one which surface id has no facets. The error is a failure we sometimes see in faceting from Cubit.

**Comment by gonuke** [comment]
Can you remind me where in the workflow this happens?  During faceting or during the loading of models into DAGMC/MOAB?

**Comment by gonuke** [comment]
I found it - this is generated by MOAB's GeomTopoTool.  I try a PR there.

**Comment by gonuke** [comment]
MOAB PR (https://bitbucket.org/fathomteam/moab/pull-requests/677)

**Comment by gonuke** [comment]
I'll let @makeclean decide whether to mark this resolved in DAGMC space and follow in MOAB space, or wait until we get a new MOAB release to mark this done.

**Comment by makeclean** [comment]
I would say its resolved :) - thanks @gonuke
