### ISSUE TITLE
Windows CI is failing

### ISSUE THREAD

**Issue by gonuke** [svalinn/DAGMC#957]
**Describe the Bug**<br/>
Windows CI is suddenly failing.  It may be due to outdated versions of some GH actions due to updates in the Windows runner

**Comment by gonuke** [comment]
It looks like updating actions is not enough 😟

The primary symptom is that it fails to find the `pyne.cpp`.   I don't know the root cause, but it could be related to:
* not properly updating the submodule
* not running the custom amalgamate correctly

**Comment by pshriwise** [comment]
I poked around a bit in a [`tmate`](https://github.com/mxschmitt/action-tmate) session. It appears that the GHA Windows runner cannot find the version of bash we're prescribing here:

https://github.com/svalinn/DAGMC/blob/7e1cdb638b59ba22fd6ff0b09e94d8f658a1eadf/src/pyne/CMakeLists.txt#L4-L7

Inside the `tmate` session, changing that hardcoded path to the `bash.EXE` to `bash` resulted in a successful CMake configuration. I'm not 100% sure this will work for all cases, but I think Windows native support for shell has become good enough that it's safe to rely on this.

**Comment by pshriwise** [comment]
Got a successful run with that tweak here: https://github.com/pshriwise/DAGMC/actions/runs/9994402642

Commit: https://github.com/pshriwise/DAGMC/commit/e4486acc16d414c138dbdf61fb35dd5bc95b77be
